import React from 'react'
import PagesTitle from '../../Components/PagesTitle'

import OAVpic from '../../Assets/imgs/OAV.jpg'
const OAV = () => {
    return (
        <div>
            <PagesTitle
                title='OAV biz haqimizda'
            />
            <div className="main paddingTop50">
                <div className="black serif  bigTitle">
                    TA’LIM MAZMUNI YARATUVCHAN VA MAS’ULIYATLI FUQARO PORTRETINI MO‘LJALGA OLGAN
                </div>
                <div className="black paddingTop50">
                    So‘nggi o‘n yilliklarda inson intellektining ahamiyati oshib, iqtisodiyot bilimga asoslangan sanoatlar ixtiyoriga o‘tmoqda. Yangi texnologiyalar va raqamli tarmoqda axborot oqimining tezlashishi va tahlil qilinishi, bilimning keng hajmda ishlab chiqarilishi, tezkor yoyilishi kuzatilmoqda. Jahonning aksar maktablari o‘quvchilarni sanoat davri uchun tayyorlashayotgan bir paytda, jamiyat allaqachon axborot texnologiyalari davrida yashamoqda. Bu davrga mos kadrlarni yetishtirish ta’lim tizimini quyidan isloh qilishni talab qiladi. Vaqt, resurs hamda sa’y-harakat hisobga olinsa, yuqori malakali kadrni voyaga yetkazish har bir davlatga qimmatga tushmoqda. Aqliy mehnat sohalarida axborotni anglash va o‘zlashtirish juda muhimligi, bunday ko‘nikmalarni bolalikdanoq shakllantirish zarurati maktab ta’limini mamlakatning hayot-mamot masalasiga aylantirdi. <br />
                    O‘zbekiston Respublikasining ta’lim sohasidagi bugungi islohotlari natijasida yaqindagina xalq ta’limi tizimiga "Prezident maktabi", "Ijod maktabi", "Zamonaviy maktab" tushunchalari kirib kelmoqda, yangi maktablar qurilishi uchun tarixda kuzatilmagan miqdorda mablag‘lar ajratilmoqda. Albatta, zamonaviy ta’lim maskanlaridagi o‘quvchilarning taqdirini ta’lim mazmuni, o‘qituvchining pedagogik mahorati belgilab beradi. <br />
                    O‘zbekiston Respublikasi Prezidenti Shavkat Mirziyoyevning Oliy Majlisga Murojaatnomasida maktab o‘quv dasturlarini ilg‘or xorijiy tajriba asosida takomillashtirish, o‘quv yuklamalari va fanlarni qayta ko‘rib chiqish, ularni xalqaro standartlarga moslashtirish, darslik va adabiyotlar sifatini oshirish zarurligi ta’kidlandi. <br />
                    Kasblar soni chegaralangan, inson qobiliyatining bugun egallangan sarhadlari hali noma’lum bo‘lgan davrlarda, maktabning vazifasi odamlarni savodli qilishdan, ularga bilim berishdan iborat bo‘lgan. Bugun esa har birimiz hayot tarzimiz, ishlashimiz va o‘zaro munosabatimizni tubdan o‘zgartirgan texnologik inqilob jarayoniga guvoh bo‘lyapmiz. Bu jarayon ko‘lami, maqsadi va murakkabligiga ko‘ra, insoniyat shu vaqtgacha boshidan o‘tkazgan o‘zgarishlarga o‘xshamaydi. Natijada, bugungi o‘zgarishlarga moslashish, o‘zgarishlarni boshlab berish uchun savodli bo‘lishning o‘zi kifoya qilmaydi. <br />
                    Bugun ta’lim konsepsiyasini ishlab chiqishda maktabni savodli inson tayyorlovchi institutdan, ko‘nikma shakllantiruvchi institutga aylantirish tamoyiliga tayanilmoqda. Natijada, maktab jamiyat XXI asr mutaxassisidan talab qilayotgan ko‘nikmalar shakllanadigan hal qiluvchi maskanga aylandi. <br />
                    O‘tgan yillar mobaynida xalq ta’limi tizimida yo‘l qo‘yilgan kamchiliklardan biri – maktab ta’limini qamrab oluvchi va mazmunini yaqqol ifodalaydigan yaxlit dastur ishlab chiqilmagan. O‘quvchi maktabni bitirguniga qadar egallaydigan ko‘nikmalari, bilimlari bilan birga, o‘qituvchilarga o‘quvchilarning o‘zlashtirishini kuzatishlari va yordamlashishlari uchun me’yorlar jam qilingan yagona ta’lim dasturining samaradorligi qator mamlakatlar tajribasida o‘zini oqlagan.<br />
                    Shuni hisobga olib, ayni paytda O‘zbekiston Respublikasi Xalq ta’limi vazirligi boshchiligida Milliy o‘quv dasturining loyihasi ishlab chiqilmoqda. Mazkur hujjat zamonaviy o‘quvchi egallashi kerak bo‘lgan to‘rt muhim jihatning rivojlanishini ta’minlaydi. Bular – tanqidiy fikrlash, ijodiy yondashish, hamkorlik o‘rnatish va muloqot qilish ko‘nikmalari. Milliy o‘quv dasturida maktab bitiruvchisiga talablar, o‘quv yuklamalari, o‘qitish metodikasi va baholash tizimi belgilab beriladi.<br />
                    Bugungacha maktab o‘quvchisi o‘zlashtirayotgan 21 ta fanlarga oid 51 ta kompetensiyani egallashi lozim bo‘lgan. Ularning aksariyati bir-birini takrorlagan, aniq ifodalanmagan edi. Xalqaro tajribani hisobga olib, xususan Buyuk Britaniyaning Kembrij universiteti mutaxassislari ishtirokida bu talab qayta ko‘rildi. Milliy o‘quv dasturida fanlarning maqsadidan kelib chiqib, o‘quvchiga beshta: filologiya, ijtimoiy-gumanitar, aniq, tabiiy va iqtisodiy va amaliy fanlar yo‘nalishlari bo‘yicha yagona talab qo‘yiladi.<br />
                    Milliy o‘quv dasturini tayyorlashda yana bir muhim jihat hisobga olindi – endi har bir sinf bo‘yicha o‘quvchining o‘quv faoliyati natijalariga qo‘yiladigan talablar, ya’ni o‘quv yili yakunida o‘quvchi qanday ko‘nikmaga ega bo‘lishi belgilanadi. Amaldagi ta’lim standartlarida bu ko‘zda tutilmagan bo‘lib, bitiruvchiga nisbatan umumiy talab qo‘yilgan. Bu esa o‘quvchidagi rivojlanishni baholashda qiyinchilik tug‘dirgan.<br />
                    Har bir sinf kesimida mavzularning aniq-tiniq belgilab berilishi o‘qituvchida o‘quvchining o‘zlashtirishini baholashga, yangi mavzuga o‘tganda avvalgi mavzuni tushunmaganlik ehtimolini kamaytirishga yoki bir xil mavzuni bir necha marotaba takrorlamaslikka xizmat qiladi. Bu yo‘nalishda xorijiy tajriba o‘rganilganida, rivojlangan davlatlar ta’lim standartlarida fanga oid darslikning muayyan qismida o‘quvchining nima o‘rganishi ham tasvirlangani ma’lum bo‘ldi. Kelgusida bu tajribani ham faoliyatimizda tatbiq etish rejasi mavjud.<br />
                    Tadqiqotlar maktab o‘quvchisi uyga vazifa uchun ikki soatdan ortiq sarflamasligi zarurligini ko‘rsatmoqda. O‘quv yuklamalarining ko‘payishi o‘quvchida tushkunlik, zo‘riqish, jismoniy nosog‘lomlik hamda o‘zlashtirishida muvozanatning buzilishiga, dars sifatining pasayishiga sabab bo‘ladi.<br />
                    O‘quv yuklamalarining maqbullashtirilishi o‘quvchining fanni yaxshi o‘zlashtirishiga xizmat qiladi. Amaliyotda 5-sinf o‘quvchilariga 17 tagacha fanning o‘qitilgani kuzatilgan. Bugun maktablarimizdagi fanlar soni ham qayta ko‘rib chiqilmoqda. Aksariyat rivojlangan davlatlarda o‘quvchilar o‘rtacha 12 ta fanni o‘zlashtiradilar. Shuni hisobga olib, 2019-2020-o‘quv yilining 3-choragidan boshlab, 10-11-sinflarda variativ o‘quv reja tajriba-sinovi boshlandi. Bunda o‘quvchi majburiy fanlarni rejali o‘qishdan voz kechib, qiziqishlariga ko‘ra tanlov yo‘nalishiga kiritilgan fanlarni o‘qiydi. Natijada, o‘quvchilar yaxshi ko‘rgan, qiziqqan fanlarni o‘qiydi, o‘qishga motivatsiyasi oshadi va shu bilan birga bitiruvchilarning oliy o‘quv yurtiga kirish imtihonlari uchun tayyorgarlik ko‘rishlariga imkoniyat yaratiladi.<br />
                    Maktabni tamomlayotgan bolaning xotirasida bu yerda olgan bilimlarining bir qismigina qoladi. Ammo o‘n bir yillik ta’lim mobaynida orttirilgan ko‘nikmalardan har bir inson umri davomida foydalanadi. Albert Eynshteyn aytgani kabi, ta’lim – maktabda o‘rganganlarimizni unutgach, yodimizda qoladigan ko‘nikmadir. Yangilik va kashfiyotlar eng ko‘p qilinayotgan davlat fuqarolari "yaratuvchan nou-hau ko‘nikmalari"ga ega, ya’ni ular innovatsion fikrlab, yangilik kiritish ishtiyoqi bilan yashashadi.<br />
                    Bugun ko‘pchilik davlatlar shaxsda hayot uchun zarur ko‘nikmalarni shakllantirishni mo‘ljalga olgan maktab ta’limini joriy qilishmoqda. Bunday ta’limning bitiruvchisi turli vaziyatlarda mas’uliyatni qo‘rqmay zimmasiga olishiga, g‘ayrat va iroda bilan muammoga yechim topishiga yordam beradigan bilim va ko‘nikmalarni egallashi kerak. Bilishga oid ko‘nikmalar sirasiga tanqidiy fikrlash, muammolarni yechish, bilimlarni qo‘llash, yaratuvchanlik va tadbirkorlik, shuningdek shaxsiy ko‘nikmalar sirasiga muloqot qilish va hamkorlik o‘rnatish, yetakchilik, mustaqil o‘rganishga bo‘lgan ishtiyoq kabi ko‘nikmalarni keltirish mumkin. Ayni paytda rivojlangan davlatlardan Kanada, Germaniya, Shveysariya, shuningdek rivojlanayotgan davlatlardan Vetnam shunday ta’lim tizimiga o‘tgan.<br />
                    Bolalarda bunday ko‘nikmalarni shakllantirishda har xil usullardan foydalanilmoqda. Xususan, Xitoyda darsliklarga PISA (O‘quvchilarni baholashning xalqaro dasturi) testlarini joriy qilish, Avstraliyada onlayn platformalar orqali o‘quvchilarning tanqidiy fikrlash ko‘nikmalarini baholash, Singapurda bu ko‘nikmalarni o‘rgatishni ta’lim dasturlariga kiritish ma’qul ko‘rilgan. Singapur tajribasiga ko‘ra, avval o‘quvchida zamon talab qilayotgan ko‘nikmalarni shakllantiruvchi darslik yaratiladi, shundan so‘ng pedagoglarning bilim va malakasi oshiriladi.<br />
                    Xalq ta’limi vazirligi tomonidan darsliklarni yaratishning maqbul mexanizmlari sinovdan o‘tkazilmoqda. Yangidan tuzilayotgan darsliklarda o‘quvchining texnologik va media ko‘nikmalarga ega bo‘lishi, yaratuvchanlik va tadbirkorlik ruhida kamol topishi, axborotni tahlil qilishi, yangi yechimlarni ilgari surishi, o‘zgarishlarga tez moslashishiga yordam beradigan bilim va ko‘nikmalar kiritilmoqda. Bunda STEAM fanlarini o‘qitish takomillashtirilayotganini muhim strategiya deyish mumkin.<br />
                    So‘nggi 50 yildirki ilm va texnologiya turmush tarzimizni o‘zgartirayotgan, jamiyatni rivojlantirayotgan drayver vazifasini o‘tab kelmoqda. Jahondagi yirik kompaniyalarning faoliyati ham ilmiy fanlar, xususan fizika, texnologiya, muhandislik, matematikaga asoslangan. Shu bilan birga, bilimlarni ijodiy yondashish orqali hayotda qo‘llashda san’atning o‘rni yuqori. Dunyo miqyosida mamlakatlar ta’limi shu fanlarni -- STEAM ta’limini o‘qitishga ixtisoslashmoqda. Butun jahonda STEAM ta’limi ishsizlik va qashshoqlikning oldini oladigan yechim sifatida ko‘rilmoqda. Sababi mazkur fanlar bilan bog‘liq ish o‘rinlari so‘nggi o‘n yilda o‘rtacha 14% ga ortgan, ya’ni boshqa mehnat sohalariga qaraganda o‘sish sur’ati 5-8% ga yuqori. Shuni hisobga olib, mamlakatimizda ham ushbu fanlarni o‘qitishda yangicha yondashuvlar joriy qilinmoqda.<br />
                    Tadqiqotlar bugungi o‘quvchilarda ko‘rib tushunish qobiliyati rivojlanib borayotganini ko‘rsatmoqda. Yangi darsliklarda tuzuvchilardan bilimlarni vizual ma’lumot orqali yetkazishga e’tibor berish so‘ralmoqda. 2019-yildan boshlab darsliklarga "QR-kod" funksiyasi joriy qilindi. Bu orqali o‘quvchi mavzu batafsil yoritilgan internet manbalarga yo‘naltiriladi. Shuningdek, yangi avlod darsliklarida "to‘ldirilgan borliq" texnologiyasidan foydalanish ko‘zda tutilgan. Endi smartfon yoki boshqa devayslardan ta’lim olishda samarali foydalanish mumkin bo‘ladi. Interaktiv raqamli darsliklar o‘quvchining diqqatini saqlashga, ko‘rib tushunishga yordam beradi. <br />
                    Bugun mamlakatimiz ta’lim tizimi oldiga yaratuvchan va ijodiy fikrlaydigan insonni voyaga yetkazish, unda tadbirkorlik ko‘nikmasini, shuningdek zarur paytda mas’uliyatni zimmasiga olish fazilatini shakllantirish talabi qo‘yilmoqda. Bu fuqaro yangi g‘oyalarni olg‘a suradi, yangi xizmat va mahsulotlarni yaratadi, shuning barobarida, odamlarni ish bilan ta’minlab, o‘ziga va jamiyatga naf keltiradi. Xalq ta’limi tizimida zamonaviy ta’lim mazmunini ishlab chiqishda aynan ana shu fuqaro portreti mo‘ljalga olingan, nazarda tutilgan. <br />
                    <div className='fw700'>
                        Shuhrat Sattorov, <br />
                        O‘zbekiston Respublikasi <br />
                        Xalq ta’limi vazirligi huzuridagi<br />
                        Respublika ta’lim markazi<br />
                        direktori o‘rinbosari<br />
                    </div>

                    <div className='paddingTop50'>
                        "Yangi O‘zbekiston" gazetasining 2020-yil, 14-fevral sonida chop etilgan

                    </div>
                    <img src={OAVpic} alt="Rasm" />
                </div>
            </div>
        </div>
    )
}

export default OAV